ruby2-1:
  image: "ruby:2.1"
  script:
    - bundle exec rake test

ruby2-3:
  image: "ruby:2.3"
  script:
    - bundle exec rake test

services:
  - couchdb:1.6.1

# Cache gems in between builds
cache:
  key: shared
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - curl -s couchdb:5984
  - git submodule update --init
  - cp config/ci/gitlab/couchdb.yml config/couchdb.admin.yml
  - cp config/ci/gitlab/couchdb.yml config
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor --without development debug
  - bundle exec rake RAILS_ENV=test db:rotate
  - bundle exec rake RAILS_ENV=test db:migrate
