dev_ca: &dev_ca
  client_ca_key: "./certs/test/files/ca.key"
  client_ca_cert: "./certs/test/files/ca.crt"
  ca_key_password: nil

cert_options: &cert_options
  client_cert_lifespan: 2
  client_cert_bit_size: 2024
  client_cert_hash: "SHA256"
  allow_limited_certs: false
  allow_unlimited_certs: true
  allow_anonymous_certs: false
  limited_cert_prefix: "LIMITED"
  unlimited_cert_prefix: "UNLIMITED"

development:
  <<: *dev_ca
  <<: *cert_options
  admins: [admin, admin2]
  domain: example.org
  secret_token: '550df064dbc5052d9e192b324c1c5a1095c85a2195f88bd6f6829c63b74d8dffa4556494a2e8cc44345a1926be8b6cb17aa4b3f3102d826f5679c3fb57bb7100'

test:
  <<: *dev_ca
  <<: *cert_options
  admins: [admin, admin2]
  domain: test.me
  secret_token: '550df064dbc5052d9e192b324c1c5a1095c85a2195f88bd6f6829c63b74d8dffa4556494a2e8cc44345a1926be8b6cb17aa4b3f3102d826f5679c3fb57bb7100'

production:
  <<: *cert_options
  admins: []
  domain: example.net
